Fix tests build for in-tree mode
When building the tests in-tree, the build fails with:

  bazel-out/darwin-fastbuild/bin/plugins/rate-limiter/rate-limiter_testsTestSuite.java:6: error: '{' expected
  public class rate-limiter_testsTestSuite {}

due to the hyphen in the test target name.

Replace it with underscore.

Change-Id: I4a0a6fc45b20ec1fca8fea7ce92230b1af3de8af